# .github/workflows/python-tests.yml
name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-django:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-django pytest-cov
        pip install -r ../requirements.txt
    
    - name: Run Django tests
      run: |
        python manage.py test
        
    - name: Run pytest with coverage
      run: |
        pytest demo/tests.py --cov=demo --cov-report=xml
        
  test-web-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-web-app
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r ../requirements.txt
    
    - name: Create test directory if it doesn't exist
      run: |
        mkdir -p tests
        
    - name: Run pytest
      run: |
        pytest --cov=./ --cov-report=xml